language: node_js
sudo: false
matrix:
  include:
    - node_js: node
      script:
        - npm run lint
        - npm test
    - node_js: "6"
    - node_js: "4"
cache:
  directories:
    - node_modules
before_install:
  - npm prune
  - npm update
notifications:
  email: false